<?php

namespace Database\Seeders;

use App\Models\JobRole;
use Illuminate\Database\Seeder;

class CareerSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            // Engineering (3)
            [
                'slug' => 'senior-fullstack-engineer',
                'title' => 'Senior Full-Stack Engineer',
                'department' => 'Engineering',
                'location' => 'Remote (US/EU)',
                'work_type' => 'remote',
                'employment_type' => 'full-time',
                'experience_level' => 'Senior',
                'summary' => 'We are looking for a Senior Full-Stack Engineer to join our platform team and build the core infrastructure that powers all Kaabosh products. You will work across the stack with Laravel, Vue.js, and PostgreSQL.',
                'about_team' => 'The platform team is responsible for the shared services, APIs, and infrastructure that all Kaabosh products rely on. We value clean architecture, thorough testing, and pragmatic engineering decisions.',
                'responsibilities' => [
                    'Design and implement features across the full stack using Laravel and Vue.js',
                    'Build and maintain RESTful APIs consumed by multiple products',
                    'Collaborate with product managers and designers to translate requirements into technical solutions',
                    'Write comprehensive tests and maintain high code quality standards',
                    'Participate in code reviews and mentor junior engineers',
                    'Contribute to architectural decisions and technical roadmap planning',
                ],
                'requirements' => [
                    '5+ years of professional software development experience',
                    'Strong proficiency in PHP/Laravel and modern JavaScript (Vue.js or React)',
                    'Experience with relational databases, preferably PostgreSQL',
                    'Solid understanding of RESTful API design and best practices',
                    'Experience with automated testing (PHPUnit, Jest, or similar)',
                    'Strong communication skills and ability to work in a remote-first environment',
                ],
                'nice_to_have' => [
                    'Experience with event-driven architectures and message queues (Kafka, RabbitMQ)',
                    'Familiarity with Docker, Kubernetes, and CI/CD pipelines',
                    'Contributions to open-source projects',
                    'Experience with multi-tenant SaaS platforms',
                ],
                'what_we_offer' => [
                    'Competitive salary range: $140,000 - $180,000',
                    'Equity package with 4-year vesting',
                    'Fully remote with flexible hours',
                    'Annual learning budget of $3,000',
                    'Home office setup stipend',
                    'Health, dental, and vision insurance',
                    '4 weeks PTO plus company holidays',
                ],
                'hiring_process' => [
                    'Application review (1-2 business days)',
                    'Introductory call with recruiter (30 minutes)',
                    'Technical interview with engineering manager (60 minutes)',
                    'Take-home coding exercise (4 hours max)',
                    'System design interview with senior engineers (60 minutes)',
                    'Culture fit conversation with team lead (30 minutes)',
                    'Offer decision within 48 hours',
                ],
                'salary_range' => '$140,000 - $180,000',
                'is_active' => true,
                'posted_at' => now()->subDays(7),
            ],
            [
                'slug' => 'backend-engineer',
                'title' => 'Backend Engineer',
                'department' => 'Engineering',
                'location' => 'Remote (Global)',
                'work_type' => 'remote',
                'employment_type' => 'full-time',
                'experience_level' => 'Mid-Level',
                'summary' => 'Join our Analytics team to build the data pipeline and query engine that powers Kaabosh Analytics. You will work with large datasets, optimize query performance, and build reliable data connectors.',
                'about_team' => 'The Analytics engineering team builds the data infrastructure that lets our customers turn raw data into actionable insights. We work with PostgreSQL, Redis, and Apache Kafka to process millions of events daily.',
                'responsibilities' => [
                    'Build and maintain data connectors for third-party services and databases',
                    'Optimize query execution for large datasets and complex aggregations',
                    'Implement data caching and refresh strategies for dashboard performance',
                    'Design and build APIs for the dashboard rendering and export engines',
                    'Monitor system performance and resolve production incidents',
                    'Write technical documentation for internal and external APIs',
                ],
                'requirements' => [
                    '3+ years of backend development experience with PHP or Python',
                    'Strong SQL skills and experience with database optimization',
                    'Experience with caching strategies (Redis, Memcached)',
                    'Understanding of data modeling and ETL concepts',
                    'Familiarity with message queues and asynchronous processing',
                    'Comfortable working in a fast-paced, iterative environment',
                ],
                'nice_to_have' => [
                    'Experience with data warehousing solutions (BigQuery, Snowflake, Redshift)',
                    'Familiarity with Apache Kafka or similar streaming platforms',
                    'Experience building multi-tenant systems',
                    'Background in data engineering or analytics',
                ],
                'what_we_offer' => [
                    'Competitive salary range: $110,000 - $145,000',
                    'Equity package with 4-year vesting',
                    'Fully remote with flexible hours',
                    'Annual learning budget of $3,000',
                    'Home office setup stipend',
                    'Health, dental, and vision insurance',
                    '4 weeks PTO plus company holidays',
                ],
                'hiring_process' => [
                    'Application review (1-2 business days)',
                    'Introductory call with recruiter (30 minutes)',
                    'Technical screen with team lead (45 minutes)',
                    'Take-home coding exercise (3 hours max)',
                    'Technical deep-dive interview (60 minutes)',
                    'Team meet-and-greet (30 minutes)',
                    'Offer decision within 48 hours',
                ],
                'salary_range' => '$110,000 - $145,000',
                'is_active' => true,
                'posted_at' => now()->subDays(14),
            ],
            [
                'slug' => 'frontend-engineer',
                'title' => 'Frontend Engineer',
                'department' => 'Engineering',
                'location' => 'Remote (US/EU)',
                'work_type' => 'remote',
                'employment_type' => 'full-time',
                'experience_level' => 'Mid-Level',
                'summary' => 'We are looking for a Frontend Engineer to help build and maintain the Kaabosh design system and product interfaces. You will craft performant, accessible UI components used across all Kaabosh products.',
                'about_team' => 'The frontend team works closely with design to build the component library and page templates that power every Kaabosh product. We care deeply about performance, accessibility, and developer experience.',
                'responsibilities' => [
                    'Build reusable UI components for the Kaabosh design system',
                    'Implement responsive, accessible interfaces using Vue.js and Tailwind CSS',
                    'Collaborate with designers to translate Figma designs into production code',
                    'Optimize frontend performance (bundle size, rendering, lazy loading)',
                    'Write unit and integration tests for UI components',
                    'Contribute to frontend tooling and build pipeline improvements',
                ],
                'requirements' => [
                    '3+ years of professional frontend development experience',
                    'Strong proficiency in Vue.js (Composition API) or React',
                    'Experience with Tailwind CSS or similar utility-first CSS frameworks',
                    'Solid understanding of HTML semantics and web accessibility (WCAG)',
                    'Experience with frontend testing frameworks (Vitest, Cypress, or similar)',
                    'Eye for design and attention to detail',
                ],
                'nice_to_have' => [
                    'Experience building and maintaining design systems',
                    'Familiarity with Inertia.js and server-side rendering',
                    'Experience with data visualization libraries (D3.js, Chart.js)',
                    'Understanding of motion design and animation (Framer Motion, GSAP)',
                ],
                'what_we_offer' => [
                    'Competitive salary range: $110,000 - $145,000',
                    'Equity package with 4-year vesting',
                    'Fully remote with flexible hours',
                    'Annual learning budget of $3,000',
                    'Home office setup stipend',
                    'Health, dental, and vision insurance',
                    '4 weeks PTO plus company holidays',
                ],
                'hiring_process' => [
                    'Application review (1-2 business days)',
                    'Introductory call with recruiter (30 minutes)',
                    'Technical screen with engineering manager (45 minutes)',
                    'Take-home UI challenge (3 hours max)',
                    'Live coding and design review (60 minutes)',
                    'Culture fit conversation (30 minutes)',
                    'Offer decision within 48 hours',
                ],
                'salary_range' => '$110,000 - $145,000',
                'is_active' => true,
                'posted_at' => now()->subDays(10),
            ],

            // Design (1)
            [
                'slug' => 'product-designer',
                'title' => 'Product Designer',
                'department' => 'Design',
                'location' => 'Remote (US/EU)',
                'work_type' => 'remote',
                'employment_type' => 'full-time',
                'experience_level' => 'Senior',
                'summary' => 'We are hiring a Product Designer to own the end-to-end design of one of our core products. You will conduct user research, create wireframes and prototypes, and work closely with engineering to ship polished experiences.',
                'about_team' => 'The design team at Kaabosh is small but mighty. We believe in research-driven design, rapid prototyping, and close collaboration with engineering. Every designer owns a product area end-to-end.',
                'responsibilities' => [
                    'Own the design for a core Kaabosh product from research through delivery',
                    'Conduct user research, usability testing, and competitive analysis',
                    'Create wireframes, prototypes, and high-fidelity designs in Figma',
                    'Collaborate with engineers to ensure designs are implemented accurately',
                    'Contribute to and evolve the Kaabosh design system',
                    'Present design rationale to stakeholders and incorporate feedback',
                ],
                'requirements' => [
                    '5+ years of product design experience in B2B SaaS',
                    'Strong portfolio demonstrating end-to-end design process',
                    'Proficiency in Figma including component libraries and prototyping',
                    'Experience with user research methods (interviews, usability testing, surveys)',
                    'Solid understanding of accessibility standards and inclusive design',
                    'Excellent communication and presentation skills',
                ],
                'nice_to_have' => [
                    'Experience designing data-heavy or analytics products',
                    'Familiarity with design tokens and design system architecture',
                    'Basic understanding of HTML, CSS, and frontend frameworks',
                    'Experience with motion design and micro-interactions',
                ],
                'what_we_offer' => [
                    'Competitive salary range: $130,000 - $165,000',
                    'Equity package with 4-year vesting',
                    'Fully remote with flexible hours',
                    'Annual learning and conference budget of $3,000',
                    'Home office setup stipend',
                    'Health, dental, and vision insurance',
                    '4 weeks PTO plus company holidays',
                ],
                'hiring_process' => [
                    'Application and portfolio review (2-3 business days)',
                    'Introductory call with recruiter (30 minutes)',
                    'Portfolio deep-dive with Head of Design (60 minutes)',
                    'Design exercise: redesign a Kaabosh feature (take-home, 4 hours)',
                    'Presentation and critique session with team (60 minutes)',
                    'Culture fit conversation with product lead (30 minutes)',
                    'Offer decision within 48 hours',
                ],
                'salary_range' => '$130,000 - $165,000',
                'requires_portfolio' => true,
                'is_active' => true,
                'posted_at' => now()->subDays(5),
            ],

            // Marketing (1)
            [
                'slug' => 'content-marketing-manager',
                'title' => 'Content Marketing Manager',
                'department' => 'Marketing',
                'location' => 'Remote (US)',
                'work_type' => 'remote',
                'employment_type' => 'full-time',
                'experience_level' => 'Mid-Level',
                'summary' => 'We are looking for a Content Marketing Manager to own the Kaabosh blog, customer stories, and educational content. You will create content that drives organic traffic, builds brand authority, and supports the sales pipeline.',
                'about_team' => 'The marketing team is a lean group of strategists, storytellers, and data-driven marketers. We believe in content that genuinely helps our audience rather than thinly veiled sales pitches.',
                'responsibilities' => [
                    'Plan and execute the editorial calendar for the Kaabosh blog',
                    'Write and edit long-form articles, tutorials, and customer case studies',
                    'Optimize content for search engines and track organic performance',
                    'Collaborate with product and engineering teams on technical content',
                    'Manage guest contributor relationships and content partnerships',
                    'Report on content performance and iterate based on data',
                ],
                'requirements' => [
                    '3+ years of content marketing experience in B2B SaaS',
                    'Excellent writing and editing skills with a portfolio of published work',
                    'Experience with SEO tools and content optimization strategies',
                    'Ability to explain complex technical concepts in accessible language',
                    'Familiarity with content management systems and analytics tools',
                    'Self-motivated with strong project management skills',
                ],
                'nice_to_have' => [
                    'Experience in the CRM, analytics, or customer support space',
                    'Familiarity with video content and webinar production',
                    'Experience with marketing automation platforms',
                    'Background in journalism or technical writing',
                ],
                'what_we_offer' => [
                    'Competitive salary range: $95,000 - $125,000',
                    'Equity package with 4-year vesting',
                    'Fully remote with flexible hours',
                    'Annual learning budget of $2,500',
                    'Home office setup stipend',
                    'Health, dental, and vision insurance',
                    '4 weeks PTO plus company holidays',
                ],
                'hiring_process' => [
                    'Application and writing samples review (2-3 business days)',
                    'Introductory call with recruiter (30 minutes)',
                    'Interview with Head of Marketing (45 minutes)',
                    'Writing exercise: draft a blog post outline and intro (take-home, 2 hours)',
                    'Content strategy discussion with marketing team (45 minutes)',
                    'Final conversation with VP of Product (30 minutes)',
                    'Offer decision within 48 hours',
                ],
                'salary_range' => '$95,000 - $125,000',
                'is_active' => true,
                'posted_at' => now()->subDays(12),
            ],

            // Sales (1)
            [
                'slug' => 'account-executive',
                'title' => 'Account Executive',
                'department' => 'Sales',
                'location' => 'Remote (US)',
                'work_type' => 'remote',
                'employment_type' => 'full-time',
                'experience_level' => 'Mid-Level',
                'summary' => 'We are hiring an Account Executive to drive new business across mid-market accounts. You will manage the full sales cycle from qualification through close, working with product-qualified leads and outbound prospects.',
                'about_team' => 'The sales team at Kaabosh practices consultative selling. We focus on understanding customer pain points and demonstrating genuine value rather than pushing features. We win by helping customers succeed.',
                'responsibilities' => [
                    'Manage full-cycle sales from lead qualification to contract close',
                    'Conduct product demonstrations tailored to prospect needs',
                    'Build and maintain a healthy sales pipeline with accurate forecasting',
                    'Collaborate with solutions engineers on technical evaluations',
                    'Negotiate contracts and pricing within established guidelines',
                    'Provide market feedback to product and marketing teams',
                ],
                'requirements' => [
                    '3+ years of B2B SaaS sales experience with a track record of quota attainment',
                    'Experience selling to mid-market companies (100-2,000 employees)',
                    'Strong discovery and consultative selling skills',
                    'Proficiency with CRM tools and sales engagement platforms',
                    'Excellent presentation and communication skills',
                    'Self-starter comfortable in a fast-paced, high-growth environment',
                ],
                'nice_to_have' => [
                    'Experience selling CRM, analytics, or customer support software',
                    'MEDDPICC or similar sales methodology training',
                    'Experience with product-led growth and hybrid sales motions',
                    'Existing relationships in the SMB/mid-market tech ecosystem',
                ],
                'what_we_offer' => [
                    'Base salary: $90,000 - $110,000 with OTE of $180,000 - $220,000',
                    'Equity package with 4-year vesting',
                    'Uncapped commission structure',
                    'Annual President\'s Club trip for top performers',
                    'Home office setup stipend',
                    'Health, dental, and vision insurance',
                    '4 weeks PTO plus company holidays',
                ],
                'hiring_process' => [
                    'Application review (1-2 business days)',
                    'Introductory call with recruiter (30 minutes)',
                    'Interview with Head of Sales (45 minutes)',
                    'Mock discovery call exercise (45 minutes)',
                    'Mock product demo with solutions engineer (45 minutes)',
                    'Final conversation with CEO (30 minutes)',
                    'Offer decision within 48 hours',
                ],
                'salary_range' => '$90,000 - $110,000 base (OTE $180,000 - $220,000)',
                'is_active' => true,
                'posted_at' => now()->subDays(8),
            ],
        ];

        foreach ($roles as $role) {
            JobRole::create($role);
        }
    }
}
